### ISSUE TITLE
strokeWidth - Double cannot be cast to String

### ISSUE THREAD

**Issue by goughjo02** [73R3WY/react-native-svg-animations#11]
Hi there,

I am using create-react-native-app CLI. Versions are:
expo: 27.0.1
react: 16.3.1
react-native: ~0.55.2
react-native-svg-animations: 0.1.6

I started a fresh project and added this package.

In App.js -  import AnimatedSVGPath from 'react-native-svg-animations' and then copy the single path example from your repo exactly.

I get the following error:

```
"Error while updating property 'strokeWidth' in shadow node of type: RNSVGPath

java.land.Double cannot be cast to java.lang.String"

UpdateShadoeNodeProp
ViewManagersPropertyCache.java:113

setProperty
viewManagerPropertyUpdater.java:58

updateProperties
ReactShadowNodeImpl.java:378

createView
UIImplementation.java:289

createView
UIManagerModule.java:366

invoke
Method.java

invoke
JavaMethodWrapper.java:372

invoke
JavaModuleWrapper.java:160

run
NativeRunnable.java

handleCallback
Handler.java:751

dispatchMessage
Handler.java:95

dispatchMessage
MessageQueueThreadHandler.java:29

loop
Looper.java:154

run
MessageQueueThreadImpl.java:192

run
Thread.java:762
```

**Comment by 73R3WY** [comment]
Hello there 😄 , seems like the latest versions of RN and Expo SDK **still** has bugs for the type casting of values. Please try using the library with the following dependencies (expo, react and react-native):  
<img width="269" alt="screen shot 2018-06-10 at 2 35 21 pm" src="https://user-images.githubusercontent.com/8436044/41198906-9ffc0f06-6cbb-11e8-9ab2-2b844c94f40c.png">

Note: I have tried using latest versions of RN and Expo to be the base dependencies of this project but I have encountered the same error as stated in your issue.

**Comment by 73R3WY** [comment]
Updated dependencies already.
