### ISSUE TITLE
Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by mikerodham** [73R3WY/react-native-svg-animations#13]
I receive this issue upon importing this in to my project.

```
    "react-native": "0.55.4",
    "react-native-svg": "^6.4.1",
    "react-native-svg-animations": "^0.1.6",
```

**Comment by 73R3WY** [comment]
This maybe caused by the SVG version or the `react-native-svg` included is the one used in Expo. See [this](https://github.com/react-native-community/react-native-svg/issues/591).

Or you can use `react-native-svg` version declared in the library dependencies block which is "react-native-svg": "^5.5.1".

**Comment by Karniej** [comment]
Is there any chance to update version of "react-native-svg" in library dependencies ?

**Comment by opiepj** [comment]
Having same issue

**Comment by LucasBassetti** [comment]
Hey @73R3WY,

I believe a simple solution can be change the `dependencies` field to `peerDependencies` in the package.json file. Some like:

```
"peerDependencies": {
    "react-native-svg": ">= 5.5.1",
    "svg-path-properties": ">= 0.4.1"
}
```

**Comment by abduraufsherkulov** [comment]
I am using expo, and apparently expo already have **react-native-svg**, therefore it kept showing redbox. However, after deleting **react-native-svg** from **react-native-svg-animation**, expo is just crashing as soon as I render the component.

**Comment by 73R3WY** [comment]
Hello @abduraufsherkulov , yes Expo already has _react-native-svg_ included, but it uses different version than the one in the library, I will look into it and update the dependencies so that it will require the latest versions of packages and also I am translating the JS code to TS.

**Comment by abduraufsherkulov** [comment]
@73R3WY Looking forward to it.

**Comment by Mr-Bhardwa7** [comment]
@mikerodham we fixed this issue on this package now you have to manually install the peer dependencies  on your project. 

@73R3WY Now you can close this task after pushing your new code on NPM.

**Comment by 73R3WY** [comment]
#16 Thank you so much @Mr-Bhardwa7
