### ISSUE TITLE
No ViewManager defined for class RNSVGPath

### ISSUE THREAD

**Issue by Tesse-rato** [73R3WY/react-native-svg-animations#14]
I used you example in 'react-native-svg-animations/examples/IngenuityPreloaderSVG'

import Example from 'react-native-svg-animations/examples/IngenuityPreloaderSVG'

<View>
  <Example />
</View>

**Comment by dimofte** [comment]
It seems to be a native code linking problem (of one of the dependencies). 
I've had the same issue, solved it by running
```
react-native link react-native-svg
cd android && ./gradlew clean
```

**Comment by 73R3WY** [comment]
Updated dependencies already, also on RN 0.60+ auto linking is enabled and I think there is no dependency that needs to be linked.
