### ISSUE TITLE
Fill svg after drawing is complete

### ISSUE THREAD

**Issue by udarts** [73R3WY/react-native-svg-animations#19]
Hi there,

How can the fill be applied after the drawing is complete. Or is this not possible?

Would be awesome to have this.

Cheers,
Stephan

**Comment by udarts** [comment]
Ok, I found a "hacky" way to get the result. Seems to be working as I expected.

**Comment by 73R3WY** [comment]
Hi @udarts , can you share what you've done to implement the svg fill after animate completion? Thanks.

**Comment by 73R3WY** [comment]
Should this be SVG path (`d`) dependent?
