### ISSUE TITLE
TypeError: t is not an Object. (evaluating 'e in t')

### ISSUE THREAD

**Issue by udarts** [73R3WY/react-native-svg-animations#23]
Hi there,

I had used this to create an svg animation and it worked in the past. Just using the default files and d.js (the content to test).

But after reinstall all plugins, I am getting a TypeError:

    TypeError: t is not an Object. (evaluating 'e in t')

I have been trying to figure out why it is happening, but could not.

Using:

    "react-native-reanimated": "^1.7.0",
    "svg-path-properties": "^1.0.2",
    "react-native-svg": "^11.0.1",
    "react-native-svg-animations": "^0.1.9",

Did someone else encountered a same issue?

**Comment by 73R3WY** [comment]
Hello, @udarts , thank you for your feedback, I will be releasing a new version after I check the merged code and test it. I think it's not the issue with the library. There could be other ext libs causing that break in code.

**Comment by udarts** [comment]
Hi @73R3WY, I have tried it with a clean install and only install this plugin and its dependencies. Still the same results.
Any idea?

Thanks

**Comment by 73R3WY** [comment]
Thank you for the feedback @udarts , I will check the code and provide an update ASAP.

**Comment by udarts** [comment]
The version I used that was still working (including dependencies):

"react-native-reanimated": "^1.4.0",
"react-native-svg": "^9.13.6",
"react-native-svg-animations": "^0.1.9"

svg-path-properties wasn't used yet in the older version (most likely the dependencies).

My guess the issue is with the combination of react-native-svg and svg-path-properties.

Hope this helps fixes it.

**Comment by 73R3WY** [comment]
Updated dependencies and tested with the latest versions of React and React Native, also created a test project implementing the library.
