### ISSUE TITLE
Cannot use 'in' operator

### ISSUE THREAD

**Issue by ezos86** [73R3WY/react-native-svg-animations#26]
![image](https://user-images.githubusercontent.com/1334598/78403409-28a84900-75b1-11ea-85d4-ede163dcb451.png)
I keep getting this, even when trying to just load the sample provided. 

Why? What is this?

**Comment by ezos86** [comment]
Seems the problem is with the svgProperties constructor. Not sure exactly, as the svgPath code is super confusing to me. But passing the length  is what the stoke offest it looking for, so I got that from the path and passed it, maybe it's wrong, I don't know. but did this, and it worked:

![image](https://user-images.githubusercontent.com/1334598/78407558-f6e7b000-75b9-11ea-8e72-f0894b933129.png)

Ideally, wouldn't need to edit the package though to make it work. :)

**Comment by 73R3WY** [comment]
Thank you @ezos86 , I'll look into this, the `svg-path-properties` dependency may be removed already, since it's only purpose is to get the length only
```javascript
this.length = properties.getTotalLength();
```
and it can be achieved using what you did.

**Comment by ezos86** [comment]
@73R3WY Yeah, it seems like that library is probably doing a lot more, I'm not sure, I believe it's checking for several Types in the SVG string, I didn't spend too much time following it, I just was looking what the return needed for the dash offset, it seems like the  .length works fine. 

Thanks for the reply, I think a lot of developers use Lotti now, but this seems like a simple nice module to use. so works for my need 👍

**Comment by pkuIleaf** [comment]
I just did 
constructor(props) {
    super(props);
    const { d, reverse } = this.props;
    // const properties = svgPathProperties(d)
    // this.length = properties.getTotalLength();
    this.length = d.length;
    this.strokeDashoffset = new Animated.Value(!reverse ? this.length : 0);
  }
and was able to resolve the issue. But animation does seems to work smoothly.

**Comment by ezos86** [comment]
> I just did
> constructor(props) {
> super(props);
> const { d, reverse } = this.props;
> // const properties = svgPathProperties(d)
> // this.length = properties.getTotalLength();
> this.length = d.length;
> this.strokeDashoffset = new Animated.Value(!reverse ? this.length : 0);
> }
> and was able to resolve the issue. But animation does seems to work smoothly.

Thanks for confirming this worked for you also. Maybe we can do a merge request to update package. @73R3WY

**Comment by 73R3WY** [comment]
Yes, @ezos86 , you guys may open a pull request to have the fix and update it in the meantime. It would be very much appreciated. I'm currently making improvements using Typescript for the library.

**Comment by art1373** [comment]
None of these solutions worked for me on 61.4 rn version it either gives the same error or gives cannot read length of undefined.

**Comment by 73R3WY** [comment]
Hi @art1373 , can you try editing the files same with the ones edited in here #27 ?

**Comment by 73R3WY** [comment]
Closing this, merged #27 and updated npm package to `0.2.1`.
