### ISSUE TITLE
Can not find variable rewind

### ISSUE THREAD

**Issue by akolpakov** [73R3WY/react-native-svg-animations#34]
In the release 0.2.3 error raises:

`Can not find variable rewind`. At the line:

https://github.com/73R3WY/react-native-svg-animations/blob/be6fcf324d7349778bd03dd0ffb2558ac3c12ff9/components/AnimatedSVGPath/index.js#L67

Reproduced on iPhone 6 real device.

seems `rewind` was not extracted from props

**Comment by 73R3WY** [comment]
Thank you @akolpakov , I will provide a quick patch.

**Comment by 73R3WY** [comment]
Published 0.2.4
