### ISSUE TITLE
Feature Request: strokeLineCap prop

### ISSUE THREAD

**Issue by joshua-augustinus** [73R3WY/react-native-svg-animations#42]
strokeLinecap is a prop already in react-native-svg. It basically gives you the option to make the stroke endpoint rounded if you want. Is this feature possible? Thanks.

**Comment by muh-hamada** [comment]
This is supported (you can check the code [here](https://github.com/73R3WY/react-native-svg-animations/blob/6b4565cb1523e38121d854bff78e3771beb530d0/components/AnimatedSVGPath/index.js#L15)) but the documentation is not up to date.

**Comment by muh-hamada** [comment]
Create a PR to update the doc https://github.com/73R3WY/react-native-svg-animations/pull/44

**Comment by 73R3WY** [comment]
#44
